#pragma once
enum {WEAPONTYPE_UNARMED=0,WEAPONTYPE_BASEBALLBAT=1,WEAPONTYPE_CHAINSAW=11,WEAPONTYPE_CANE=15,
 WEAPONTYPE_M16=20,WEAPONTYPE_SNIPERRIFLE=21,WEAPONTYPE_ROCKETLAUNCHER=22,WEAPONTYPE_M4=23,
 WEAPONTYPE_RUGER=24,WEAPONTYPE_LASERSCOPE=25,WEAPONTYPE_M60=26,WEAPONTYPE_CAMERA=27};
struct CWeapon{unsigned m_eWeaponType=99;};
struct CPlayerPed{CWeapon weapon;CWeapon* GetWeapon(){return &weapon;}};
inline CPlayerPed testPlayer;
